### ISSUE TITLE
Inject HTTP Client or Logger

### ISSUE THREAD

**Issue by adrienbrault** [cognesy/instructor-php#14]
Hey,

How can I inject my [PSR-3](https://www.php-fig.org/psr/psr-3/) logger and use my own Guzzle/[PSR-18](https://www.php-fig.org/psr/psr-18/) HTTP Client?

**Comment by ddebowczyk** [comment]
If your goal is to inspect requests and responses, check:
 - https://cognesy.github.io/instructor-php/hub/debugging/

In v0.6.1 Instructor offers access to Saloon's connector, so you can set your own onRequest() and onResponse() middleware - see more here:
 - https://cognesy.github.io/instructor-php/internals/http/
 - https://docs.saloon.dev/digging-deeper/middleware#request-middleware
 - https://docs.saloon.dev/digging-deeper/middleware#response-middleware

Regarding providing custom Guzzle client:

1) Create custom connector instance, e.g. OpenAIConnector and set custom sender class (via ApiConnector constructor).
```php
$connector = new OpenAIConnector(..., senderClass: YourSender::class);
```
2) Provide your connector to API client e.g.:
```php
$client = (new OpenAIClient(...))->withConnector($connector);
```
3) Now create Instructor instance with your client:
```php
$instructor = (new Instructor)->withClient($client);
```

Alternatively, you can implement custom connector and override $defaultSender property.

I have not found a lot on custom senders in Saloon docs, but check this for some info:

 - https://docs.saloon.dev/digging-deeper/middleware#guzzle-handlers-middleware
 - https://github.com/saloonphp/saloon/blob/v3/src/Http/Senders/GuzzleSender.php
 
 Let me know if this helps.

**Comment by adrienbrault** [comment]
Thank you.

I see what in order to inject my own guzzle client I need to subclass `GuzzleSender` 😔.

While Saloon advertises itself as being `Framework agnostic`, I feel like it makes it harder to integrate cleanly in a Symfony project than plain Guzzle. FYI

**Comment by ddebowczyk** [comment]
Looks like this discussion on Saloon GH issue might be relevant:
https://github.com/saloonphp/saloon/discussions/199
