### ISSUE TITLE
[Feature Request]: Configurable options for Ollama

### ISSUE THREAD

**Issue by ErroneousBosch** [cognesy/instructor-php#18]
With the inclusion of Ollama, this opens up a broader set of models, especially with a dedicated higher-power server. Could OllamaConnector options such as baseUrl/Endpoint and selected model be configurable via ENV, the way that API keys are now?

**Comment by ddebowczyk** [comment]
Thanks for the idea.

You can already configure custom base URL via constructor of OllamaClient - see OllamaClient code:
https://github.com/cognesy/instructor-php/blob/main/src/Clients/Ollama/OllamaClient.php

See example for OllamaClient (although it does not change the default config):
https://github.com/cognesy/instructor-php/blob/main/examples/05_APISupport/LLMSupportOllama/run.php

Regarding endpoint configuration - it will be configurable starting from the next release (approx next week).

The client code is currently being refactored to make future changes easier.

**Comment by ErroneousBosch** [comment]
Awesome to hear, I'll watch for it!

**Comment by ddebowczyk** [comment]
I'm wondering why do you need to customize endpoint, considering Ollama has it fixed for OpenAI compatible access (afaik), which is the only one Instructor currently supports?

**Comment by ErroneousBosch** [comment]
My one use case is running instructor on a user machine like my laptop, but running the LLM on a server that has more capability, so the ability to define where it looks for its endpoint is how this would be done.

The other use case I have is docker containers, where I can do internal routing between containers without exposing the ollama endpoint publicly.

**Comment by ErroneousBosch** [comment]
To be clear it's mostly being able to set the baseUrl and model that I am really asking for.

**Comment by ddebowczyk** [comment]
Both baseUrl and model can be set by user:

```php
$client = new OllamaClient(
   baseUri: 'your-url',
);

$instructor = (new Instructor)->withClient($client);

$result = $instructor->respond(
   messages: 'your-data',
   responseModel: YourDataModel::class,
   model: 'your-ollama-model',
);
```

**Comment by ddebowczyk** [comment]
Please let me know if it solves your problem, so the issue can be closed.

**Comment by ErroneousBosch** [comment]
That should do it, thanks
