### ISSUE TITLE
Missing docs pages 

### ISSUE THREAD

**Issue by jxnl** [cognesy/instructor-php#2]
Can just look like: https://jxnl.github.io/instructor/

- [ ] [Why](https://jxnl.github.io/instructor/why/)
- [ ] [Help](https://jxnl.github.io/instructor/help/)
- [ ] [Tips](https://jxnl.github.io/instructor/concepts/prompting/)
- [ ] [Philosophy/Concepts](https://jxnl.github.io/instructor/concepts/philosophy/)
- [ ] [Cookbook](https://jxnl.github.io/instructor/examples/)

For cookbooks really all you need is the following

1. [How are single and multi-label classifications done using enums?](https://jxnl.github.io/instructor/examples/classification/)
2. [extracting and expanding search](https://jxnl.github.io/instructor/examples/search/)
3. [supporting anyscale, ollama, together ai by updating the base_url](https://jxnl.github.io/instructor/hub/together/)

**Comment by ddebowczyk** [comment]
Done
