### ISSUE TITLE
Process Each Item in an Array of Objects as Soon as It Completes

### ISSUE THREAD

**Issue by raftx24** [cognesy/instructor-php#30]
In many scenarios, when working with an array of objects, you might want to process each item independently as soon as it finishes, rather than waiting for all items to complete. This is particularly useful when dealing with asynchronous tasks, where each operation might take varying amounts of time. If this is deemed a valuable addition, I would be happy to implement this functionality.

**Comment by ddebowczyk** [comment]
Please check Sequence::of(YourClass::class) + streaming on - I think it might be what you are looking for.
If that's not the case, feel free to suggest how this could be solved.

**Comment by ddebowczyk** [comment]
Marked for closing as it is supported out of the box for streaming.
Async is not yet supported by Instructor.
