### ISSUE TITLE
DateTime support

### ISSUE THREAD

**Issue by Toflar** [cognesy/instructor-php#32]
Looks like support for `\DateTimeInterface` is missing. Symfony supports this using the `DateTimeNormalizer` but I guess it would also need some work on the schema side of this library? :)

**Comment by ddebowczyk** [comment]
Good point Yannick. Please check:
https://docs.instructorphp.com/cookbook/examples/extras/transcription_to_tasks

If that's not what you have been looking for, please feel free to suggest how this could be fixed. This is where you might look as some starting points:
https://github.com/cognesy/instructor-php/blob/main/src/Deserialization/Deserializers/FlexibleDateDenormalizer.php
https://github.com/cognesy/instructor-php/blob/main/src/Deserialization/Deserializers/SymfonyDeserializer.php

**Comment by Toflar** [comment]
Ah, it seems like I've found the issue: `\DateTime` seems to work but `\DateTimeInterface`  and `\DateTimeImmutable` do not. I get this error when using those as type hints:

>   Validation recovery attempts limit reached after 1 attempts due to: "No deserializer found for the response"  

I never use `\DateTime` 😉

**Comment by ddebowczyk** [comment]
Try checking the 2 files I've mentioned and suggest changes, I'm swamped
with other stuff today.

W dniu śr., 2.10.2024 o 17:42 Yanick Witschi ***@***.***>
napisał(a):

**Comment by ddebowczyk** [comment]
OK, thanks for highlighting this - it's fixed in v0.9.7.
