### ISSUE TITLE
$httpClient is not assigned to $client property in the constructor of GuzzleDriver

### ISSUE THREAD

**Issue by miserenkov** [cognesy/instructor-php#34]
Hi there.

When passing a custom `$httpClient` to the constructor of the `Cognesy\Instructor\Features\Http\Drivers\GuzzleDriver` class, the `$client` property is not assigned to the provided instance of Client. Instead, a new Client instance is always created regardless of the input.

This behavior can lead to unexpected results, especially when debugging is disabled (`Debug::isEnabled() === false`). In this scenario, the expected behavior is for the `$httpClient` to be used as the `$client`.

### Steps to Reproduce:
1. Create an instance of `GuzzleDriver` with a custom `$httpClient`:
```php
$customHttpClient = new Client(['base_uri' => 'https://api.example.com']);
$driver = new GuzzleDriver($config, $customHttpClient);
```
2. Attempt to use the `$driver` instance and observe that the $client property does not reference` $customHttpClient`.

### Expected Behavior:

If `$httpClient` is provided and debugging is disabled (`Debug::isEnabled() === false`), the `$client` property should be assigned to the provided `$httpClient` instance.

### Actual Behavior:

The `$client` property is always assigned to a new instance of Client with debugging settings, even if `$httpClient` is provided and debugging is disabled.

### Environment:
• Library Version: v0.10.8
• PHP Version: 8.3

**Comment by ddebowczyk** [comment]
Thanks for reporting! I will check this out tomorrow.

**Comment by ddebowczyk** [comment]
Should be fixed now.

Also, please note that (afaik) Guzzle does not allow to inject debugging stack into existing client. Turn off debug or use default client.
